root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
#  args_bin = ["-config", "examples/config.yaml"]
  bin = "tmp/server.exe"
  cmd = "go build -o ./tmp/server.exe ./cmd/server/main.go"
  delay = 1000
  include_dir = ["cmd"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  exclude_regex = ["_test.go"]
  exclude_dir = ["web", "web"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
