package config

var defaults = map[string]string{
	"debug":                          "false",
	"dev_mode":                       "false",
	"server.port":                    "8000",
	"server.enable_cors":             "true",
	"server.tls_enabled":             "false",
	"server.tls_cert_file":           "",
	"server.tls_key_file":            "",
	"database.postgres.sslmode":      "disable",
	"database.postgres.host":         "localhost",
	"database.postgres.user":         "postgres",
	"database.postgres.password":     "postgres",
	"database.postgres.dbname":       "postgres",
	"database.postgres.port":         "5432",
	"database.postgres.auto_migrate": "true",
	"database.postgres.enabled":      "false",
	"database.sqlite.enabled":        "true",
	"database.sqlite.datasource":     "mrelay.db?_loc=auto",
	"smtp.host":                      "localhost",
	"smtp.port":                      "25",
	"smtp.username":                  "",
	"smtp.password":                  "",
	"smtp.from_name":                 "mrelay",
	"smtp.from_address":              "mrelay@localhost",
}

var envKeys = map[string]string{
	"debug":                          "DEBUG",
	"dev_mode":                       "DEV_MODE",
	"database.sqlite.enabled":        "DATABASE_SQLITE_ENABLED",
	"database.sqlite.datasource":     "DATABASE_SQLITE_DATASOURCE",
	"database.postgres.enabled":      "DATABASE_POSTGRES_ENABLED",
	"database.postgres.host":         "DATABASE_POSTGRES_HOST",
	"database.postgres.port":         "DATABASE_POSTGRES_PORT",
	"database.postgres.user":         "DATABASE_POSTGRES_USER",
	"database.postgres.password":     "DATABASE_POSTGRES_PASSWORD",
	"database.postgres.dbname":       "DATABASE_POSTGRES_DBNAME",
	"database.postgres.sslmode":      "DATABASE_POSTGRES_SSLMODE",
	"database.postgres.auto_migrate": "DATABASE_POSTGRES_AUTOMIGRATE",
	"server.port":                    "SERVER_PORT",
	"server.tls_enabled":             "SERVER_TLS_ENABLED",
	"server.tls_cert_file":           "SERVER_TLS_CERT_FILE",
	"server.tls_key_file":            "SERVER_TLS_KEY_FILE",
	"smtp.host":                      "SMTP_HOST",
	"smtp.port":                      "SMTP_PORT",
	"smtp.username":                  "SMTP_USERNAME",
	"smtp.password":                  "SMTP_PASSWORD",
	"smtp.from_name":                 "SMTP_FROM_NAME",
	"smtp.from_address":              "SMTP_FROM_ADDRESS",
}
